# Generated by Django 5.0.1 on 2024-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='candidates.tag'),
        ),
    ]
