# Generated by Django 5.0.1 on 2024-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_options_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_fake',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
