# Generated by Django 5.0.1 on 2024-06-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='candidate_photos'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_fake',
            field=models.BooleanField(default=False, editable=False, verbose_name='fake status'),
        ),
    ]
